# Copyright (c) 2020 Luca Cappa
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT
name: hosted-advanced-vcpkg-overlay
on: [push]

jobs:
  job:
    name: ${{ matrix.os }}-hosted-advanced-overlay
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
            configuration: 'x64.*'
          - os: ubuntu-latest
            triplet: x64-linux
            configuration: '.*Linux.*'
          - os: macos-latest
            triplet: x64-osx
            configuration: '.*Linux.*'

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - uses: lukka/get-cmake@latest
      - name: dir
        run: find $RUNNER_TEMP
        shell: bash
      - name: dir
        run: find $RUNNER_WORKSPACE
        shell: bash
      - name: Set vcpkg's response file path used as part of cache's key.
        uses: lukka/set-shell-env@master
        with:
          VCPKGRESPONSEFILE: ${{ github.workspace }}/cmakeliststxt/vcpkg_${{ matrix.triplet }}.txt
          VCPKGRESPONSEFILE_FOR_OVERLAYS: ${{ github.workspace }}/overlays/vcpkg.txt
          VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
          filter: ^VCPKG.*
      - name: Restore artifacts, run vcpkg using overlays
        uses: lukka/run-vcpkg@dev/cache_in_action
        id: runvcpkg
        with:
          vcpkgArguments: '@${{ env.VCPKGRESPONSEFILE }} @${{ env.VCPKGRESPONSEFILE_FOR_OVERLAYS }}'
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          # Ensure the cache key changes any time the content of the response file changes.
          appendedCacheKey: ${{ hashFiles( env.VCPKGRESPONSEFILE ) }}
      - run: |
          $VCPKG_ROOT/vcpkg install @$VCPKGRESPONSEFILE --clean-after-build
        shell: bash
        name: Run vcpkg in a inline script in this workflow.
      - name: Prints output of run-vcpkg's task
        run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_TRIPLET_OUT }}'"
      - name: Prints output of ANDROID_SDK_ROOT and ANDROID_HOME env var
        run: echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT ANDROID_HOME=$ANDROID_HOME"
        shell: bash
      - uses: lukka/set-shell-env@v1
        with:
          CXX: ${{ matrix.cxx }}
      - name: Run CMake with Ninja Multi-Config
        uses: lukka/run-cmake@use_1.0.x_packages
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/cmakeliststxt/CMakeLists.txt'
          useVcpkgToolchainFile: true
          buildDirectory: '${{ runner.workspace }}/b/ninjaMultiConfig'
          cmakeAppendedArgs: '"-GNinja Multi-Config" -DVCPKG_TARGET_TRIPLET=${{ env.VCPKG_DEFAULT_TRIPLET }} '
          buildWithCMake: true
      - name: Run CMake+EnvVar (Un*x)
        if: "!contains( matrix.os, 'windows')"
        uses: lukka/run-cmake@use_1.0.x_packages
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/cmakeliststxt/CMakeLists.txt'
          useVcpkgToolchainFile: true
          buildDirectory: '${{ runner.workspace }}/b/envvar_ninja'
          cmakeAppendedArgs: '-GNinja -DVCPKG_TARGET_TRIPLET=${{ env.VCPKG_DEFAULT_TRIPLET }} -DCMAKE_TOOLCHAIN_FILE=${ANDROID_HOME}/ndk-bundle/build/cmake/android.toolchain.cmake'
          buildWithCMake: false
      - name: Run CMake+EnvVar (Win)
        if: "contains( matrix.os, 'windows')"
        uses: lukka/run-cmake@use_1.0.x_packages
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/cmakeliststxt/CMakeLists.txt'
          useVcpkgToolchainFile: true
          buildDirectory: '${{ runner.workspace }}/b/envvar_ninja'
          cmakeAppendedArgs: '-GNinja -DVCPKG_TARGET_TRIPLET=${{ env.VCPKG_DEFAULT_TRIPLET }} -DCMAKE_TOOLCHAIN_FILE=%ANDROID_NDK_HOME%/build/cmake/android.toolchain.cmake'
          buildWithCMake: false
      - name: Run CMake+Ninja
        uses: lukka/run-cmake@use_1.0.x_packages
        id: runcmake
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/cmakeliststxt/CMakeLists.txt'
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          useVcpkgToolchainFile: true
          buildWithCMakeArgs: '-- -v'
          buildDirectory: '${{ runner.workspace }}/b/ninja/'
          cmakeAppendedArgs: '-GNinja -DVCPKG_TARGET_TRIPLET=${{ env.VCPKG_DEFAULT_TRIPLET }}'
      - name: Run CMake+VS
        uses: lukka/run-cmake@use_1.0.x_packages
        if: contains( matrix.os, 'windows')
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/cmakeliststxt/CMakeLists.txt'
          useVcpkgToolchainFile: true
          buildDirectory: '${{ runner.workspace }}/b/vs16'
          cmakeAppendedArgs: '"-GVisual Studio 16 2019" -Ax64 -DVCPKG_TARGET_TRIPLET=${{ env.VCPKG_DEFAULT_TRIPLET }} '
      - name: 'Run CMake with CMakeSettings.json'
        uses: lukka/run-cmake@use_1.0.x_packages
        with:
          cmakeListsOrSettingsJson: CMakeSettingsJson
          cmakeSettingsJsonPath: '${{ github.workspace }}/cmakesettingsjson/CMakeSettings.json'
          useVcpkgToolchainFile: true
          configurationRegexFilter: ${{ matrix.configuration }}
          cmakeAppendedArgs: '-DVCPKG_TARGET_TRIPLET=${{ env.VCPKG_DEFAULT_TRIPLET }}'

